language: python
python:
  - "3.6"

services:
  - docker

before_install: 
  - pip install docker-compose
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
