# Generated by Django 2.1.15 on 2021-01-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='mame',
            new_name='name',
        ),
    ]
